export const EXAMPLES_SEARCH_BOOK_BEGIN = 'EXAMPLES_SEARCH_BOOK_BEGIN';
export const EXAMPLES_SEARCH_BOOK_SUCCESS = 'EXAMPLES_SEARCH_BOOK_SUCCESS';
export const EXAMPLES_SEARCH_BOOK_FAILURE = 'EXAMPLES_SEARCH_BOOK_FAILURE';
export const EXAMPLES_SEARCH_BOOK_DISMISS_ERROR = 'EXAMPLES_SEARCH_BOOK_DISMISS_ERROR';
