export const EXAMPLES_SEARCH_BOOK_BEGIN = 'EXAMPLES_SEARCH_BOOK_BEGIN';
export const EXAMPLES_SEARCH_BOOK_SUCCESS = 'EXAMPLES_SEARCH_BOOK_SUCCESS';
export const EXAMPLES_SEARCH_BOOK_FAILURE = 'EXAMPLES_SEARCH_BOOK_FAILURE';
export const EXAMPLES_SEARCH_BOOK_DISMISS_ERROR = 'EXAMPLES_SEARCH_BOOK_DISMISS_ERROR';
export const EXAMPLES_SEARCH_NEXT_PAGE_BEGIN = 'EXAMPLES_SEARCH_NEXT_PAGE_BEGIN';
export const EXAMPLES_SEARCH_NEXT_PAGE_SUCCESS = 'EXAMPLES_SEARCH_NEXT_PAGE_SUCCESS';
export const EXAMPLES_SEARCH_NEXT_PAGE_FAILURE = 'EXAMPLES_SEARCH_NEXT_PAGE_FAILURE';
export const EXAMPLES_SEARCH_NEXT_PAGE_DISMISS_ERROR = 'EXAMPLES_SEARCH_NEXT_PAGE_DISMISS_ERROR';
