export const BOOKS_SEARCH_BOOK_BEGIN = 'BOOKS_SEARCH_BOOK_BEGIN';
export const BOOKS_SEARCH_BOOK_SUCCESS = 'BOOKS_SEARCH_BOOK_SUCCESS';
export const BOOKS_SEARCH_BOOK_FAILURE = 'BOOKS_SEARCH_BOOK_FAILURE';
export const BOOKS_SEARCH_BOOK_DISMISS_ERROR = 'BOOKS_SEARCH_BOOK_DISMISS_ERROR';
export const BOOKS_GET_BOOK_BEGIN = 'BOOKS_GET_BOOK_BEGIN';
export const BOOKS_GET_BOOK_SUCCESS = 'BOOKS_GET_BOOK_SUCCESS';
export const BOOKS_GET_BOOK_FAILURE = 'BOOKS_GET_BOOK_FAILURE';
export const BOOKS_GET_BOOK_DISMISS_ERROR = 'BOOKS_GET_BOOK_DISMISS_ERROR';
